services:
  pititi-bot:
    image: ghcr.io/reboundq3/pititi-bot:latest #Change this to your own, or use mine for upstream
    container_name: pititi-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/Databases  # Persist databases between container restarts
    environment:
      - HOME=/app  # Ensure working directory is correctly set
